version: '3.8'
services:
  fastapi-app:
    build: .
    container_name: fastapi_app
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: uvicorn main:app --host=0.0.0.0 --port=8001 --reload